steps:
  - id: "Buildpack"
    name: "gcr.io/k8s-skaffold/pack"
    args:
      - "build"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/interns-management-system/interns360:$SHORT_SHA"
      - "--builder=gcr.io/buildpacks/builder:latest"
      - "--path=."
      - "--env"
      - "GOOGLE_ENTRYPOINT=python backend/main.py"

  - id: "Push"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/interns-management-system/interns360:$SHORT_SHA"

  - id: "Deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "interns360"
      - "--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/interns-management-system/interns360:$SHORT_SHA"
      - "--region=europe-west1"
      - "--platform=managed"
      - "--allow-unauthenticated"

tags:
  - "interns360"
