steps:
  - id: "Buildpack"
    name: "gcr.io/k8s-skaffold/pack"
    args:
      - "build"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/interns-management-system/interns360:$SHORT_SHA"
      - "--builder=gcr.io/buildpacks/builder:latest"
      - "--path=."
      - "--env"
      - "GOOGLE_ENTRYPOINT=python start.py"

  - id: "Push"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/interns-management-system/interns360:$SHORT_SHA"

  - id: "Deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "interns360"
      - "--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/interns-management-system/interns360:$SHORT_SHA"
      - "--region=europe-west1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8000"
      - "--set-env-vars=PORT=8000,RELOAD=false"
      - "--timeout=600"
      - "--cpu=2"
      - "--memory=1Gi"
      - "--set-secrets=MONGODB_URL=mongodb-url:latest,SECRET_KEY=jwt-secret:latest,AZURE_SECRET_KEY=azure-secret:latest"

tags:
  - "interns360"
options:
  machineType: "N1_HIGHCPU_8"
